version: '3'
services:
  web:
    image: ynab_graphql_dev
    command: "/bin/sh -c 'rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0'"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/var/ynab_graphql
    depends_on:
      - redis
  redis:
    image: redis:4-alpine
